config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from multidb.products import views
urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    url(
        r"^about/$",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(
        r"^users/",
        include("multidb.users.urls", namespace="users"),
    ),
    url(
        r"^products/",
        include("multidb.products.urls", namespace="products"),
    ),
    url(r"^accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

multidb/products/urls.py
from django.conf.urls import url

from . import views

app_name = "products"
urlpatterns = [
    url(regex=r"^$", view=views.ProductList.as_view(), name="list"),
    url(regex=r"^create/$", view=views.ProductCreate.as_view(), name="create"),
    url(regex=r"^(?P<db>[\w.@+-]+)/update/(?P<pk>\d+)/$", view=views.ProductUpdate.as_view(), name="update"),
    url(regex=r"^(?P<db>[\w.@+-]+)/delete/(?P<pk>\d+)/$", view=views.ProductDelete.as_view(), name="delete"),
]

multidb/users/urls.py
from django.conf.urls import url

from . import views

app_name = "users"
urlpatterns = [
    url(regex=r"^$", view=views.UserListView.as_view(), name="list.html"),
    url(regex=r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    url(regex=r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),
    url(
        regex=r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

multidb/products/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    user = models.IntegerField()

    def __str__(self):
        return self.name

multidb/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class Database(models.Model):
    name = models.CharField(_("Name of Database"),max_length=255)

    def __str__(self):
        return self.name


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    databases = models.ManyToManyField(Database)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

multidb/products/forms.py
from django import forms

from .models import Product
from multidb.users.models import User


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description',)

multidb/products/views.py
from django.db.models import Value, CharField
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import Product
from multidb.users.models import User
from .forms import ProductForm


class ProductCreate(LoginRequiredMixin, CreateView):
    template_name = 'product/create.html'
    model = Product
    form_class = ProductForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        instance = form.save(commit=False)
        instance.user = request.user.id
        database = request.POST['database']
        instance.save(using=database)
        return redirect(reverse("products:list"))

    def get_context_data(self, **kwargs):
        ctx = super(ProductCreate, self).get_context_data(**kwargs)
        databases = self.request.user.databases.all()
        ctx['databases'] = databases
        return ctx


class ProductList(LoginRequiredMixin, ListView):
    template_name = 'product/list.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        dbs = self.request.user.databases.all()
        product_list = []
        for d in dbs:
            products = Product.objects.using(d.name).filter(user=self.request.user.id).values('id', 'name', 'description').annotate(db=Value(d.name, output_field=CharField()))
            product_list.extend(products)
        context['product_list'] = product_list
        return context


class ProductUpdate(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        instance = Product.objects.using(kwargs['db']).get(pk=kwargs['pk'])
        instance.name = request.POST['name']
        instance.description = request.POST['description']
        instance.save(using=kwargs['db'])
        return redirect(reverse("products:list"))

    def get(self, request, *args, **kwargs):
        instance = Product.objects.using(kwargs['db']).get(pk=kwargs['pk'])
        form = ProductForm(initial={'name': instance.name, 'description':instance.description})
        return render(request, 'product/update.html', {'form': form})


class ProductDelete(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        instance = Product.objects.using(kwargs['db']).get(pk=kwargs['pk'])
        instance.delete(using=kwargs['db'])
        return redirect(reverse("products:list"))

multidb/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ["name"]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

multidb/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

multidb/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}multidb{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}

    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">multidb</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
{#              <li class="nav-item">#}
                {# URL provided by django-allauth/account/urls.py #}
{#                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>#}
{#              </li>#}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

multidb/templates/pages/about.html
{% extends "base.html" %}

multidb/templates/pages/home.html
{% extends "base.html" %}

multidb/templates/product/create.html
{% extends 'base.html' %}
{% block content %}
    <h1>New Product</h1>
    <hr/>
    <form method="POST" class="post-form">
        <select name="database">
            {% for d in databases %}
                <option value="{{ d }}">{{ d }}</option>
            {% endfor %}
        </select>
        <br>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">Save</button>
    </form>
{% endblock %}

multidb/templates/product/list.html
{% extends 'base.html' %}
{% block content %}
    <div class="page-header">
    <h1 style="margin: 0px;display: inline-block">Products</h1>
    <a href="{% url 'products:create' %}" class="btn btn-primary" style="float: right; margin-top: 5px;"> Create Product</a>
    </div>
    <hr/>
    <table style="width:100%">
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>DB</th>
            <th>Action</th>
          </tr>
    {% for object in product_list %}
          <tr>
            <td>{{ object.name }}</td>
            <td>{{ object.description }}</td>
            <td>{{ object.db }}</td>
              <td>
                  <a href="{% url 'products:update' db=object.db pk=object.id %}" class="btn btn-primary btn-sm" style="display: inline">Edit</a>
                  <form method="post" action="{% url 'products:delete' db=object.db pk=object.id %}" style="display: inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                  </form>
              </td>
          </tr>
    {% endfor %}
     </table>
{% endblock %}

multidb/templates/product/update.html
{% extends 'base.html' %}
{% block content %}
    <h1>Edit Product</h1>
    <hr/>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">Save</button>
    </form>
{% endblock %}

multidb/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

multidb/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

multidb/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}